### ISSUE TITLE
get error TypeError: Cannot read property 'node' of undefined when i run custom polka runtime parse

### ISSUE THREAD

**Issue by baidang201** [KYVENetwork/kyve#8]
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'node' of undefined
    at KYVE.<anonymous> (/node_modules/@kyve/core/dist/index.js:178:43)
    at step (/node_modules/@kyve/core/dist/index.js:33:23)
    at Object.next (/node_modules/@kyve/core/dist/index.js:14:53)
    at fulfilled (/node_modules/@kyve/core/dist/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
01:27:30 info[validator]:  Buffer size is now: 50

find the vesion in  integrations/node/package.json is "@kyve/core": "0.0.0-alpha.16",

**Comment by johnletey** [comment]
Hey @baidang201! Thanks for pointing this out 😄

Seemed to be an issue with the Arweave GraphQL endpoint. We now catch this!
